#https://github.com/jacildoaldrin/course-material

language: node_js

node_js:
  - "10.9.0"

cache: npm

env:
  - NOW_TOKEN=sWwOgaNaBONWWk58gpnrfcf4



before_install:
  - ls -la
  - mkdir dist

install:
  - ls -la
  - npm install
  - ls -la
