#https://github.com/jacildoaldrin/course-material

language: node_js

node_js:
  - "10.9.0"

cache: npm

env:
  - NOW_TOKEN=sWwOgaNaBONWWk58gpnrfcf4

install:
  - npm install

script:
  - npm run build
  - npm run test
